network:
  version: 2
  ethernets:
    eth0:
      dhcp6: true
      dhcp6: false
      addresses: [{{ ip }}/24]
      routes:
        - to: default
          via: {{ gw }}
      nameservers:
        addresses: 
          - 8.8.8.8
          - 8.8.4.4
